# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Person.create(first_name: "Mario", last_name: "Mario", email: "mario@mario.com", job: "Plumber", bio: "On it differed repeated wandered required in. Then girl neat why yet knew rose spot. Moreover property we he kindness greatest be oh striking laughter. In me he at collecting affronting principles apartments. Has visitor law attacks pretend you calling own excited painted. Contented attending smallness it oh ye unwilling. Turned favour man two but lovers. Suffer should if waited common person little oh. Improved civility graceful sex few smallest screened settling. Likely active her warmly has.", gender: "Male", birthday: "1982-10-10", picture: "https://aff5fa4925746bf9c161-fb36f18ca122a30f6899af8eef8fa39b.ssl.cf5.rackcdn.com/images/Profile_Mario.aead314d435d8e52d9a4e92a6f799c4eee08081e.jpg")
Person.create(first_name: "Luigui", last_name: "Mario", email: "luigui@mario.com", job: "Plumber", bio: "Carried nothing on am warrant towards. Polite in of in oh needed itself silent course. Assistance travelling so especially do prosperous appearance mr no celebrated. Wanted easily in my called formed suffer. Songs hoped sense as taken ye mirth at. Believe fat how six drawing pursuit minutes far. Same do seen head am part it dear open to. Whatever may scarcely judgment had.", gender: "Male", birthday: "1983-10-10", picture: "http://vignette2.wikia.nocookie.net/mario-fanon/images/8/8e/Luigi-circle.jpg/revision/latest?cb=20130907182141&path-prefix=es")
Person.create(first_name: "Peach", last_name: "Toadstool", email: "peach@mario.com", job: "Princess", bio: "Remain lively hardly needed at do by. Two you fat downs fanny three. True mr gone most at. Dare as name just when with it body. Travelling inquietude she increasing off impossible the. Cottage be noisier looking to we promise on. Disposal to kindness appetite diverted learning of on raptures. Betrayed any may returned now dashwood formerly. Balls way delay shy boy man views. No so instrument discretion unsatiable to in. ", gender: "Female", birthday: "1984-10-10", picture: "https://pbs.twimg.com/profile_images/1409899072/OfficialPeach.jpg")
Person.create(first_name: "Bowser", last_name: "Koopa", email: "bowser@mario.com", job: "Kidnapper", bio: "Remain valley who mrs uneasy remove wooded him you. Her questions favourite him concealed. We to wife face took he. The taste begin early old why since dried can first. Prepared as or humoured formerly. Evil mrs true get post. Express village evening prudent my as ye hundred forming. Thoughts she why not directly reserved packages you. Winter an silent favour of am tended mutual. ", gender: "Male", birthday: "1983-10-10", picture: "http://yokosojapan.co.jp/wp/wp-content/uploads/2015/05/BowserTitle.png")
Person.create(first_name: "Pikachu", last_name: "Pokemon", email: "pikachu@pokemon.com", job: "Battery", bio: "He an thing rapid these after going drawn or. Timed she his law the spoil round defer. In surprise concerns informed betrayed he learning is ye. Ignorant formerly so ye blessing. He as spoke avoid given downs money on we. Of properly carriage shutters ye as wandered up repeated moreover. Inquietude attachment if ye an solicitude to.", gender: "Male", birthday: "1996-10-10", picture: "http://vignette2.wikia.nocookie.net/pokemon/images/4/48/025Pikachu_OS_anime.png/revision/latest?cb=20150717063915")
Person.create(first_name: "Charizard", last_name: "Pokemon", email: "charizard@pokemon.com", job: "Flamethrower", bio: "Talking chamber as shewing an it minutes. Trees fully of blind do. Exquisite favourite at do extensive listening. Improve up musical welcome he. Gay attended vicinity prepared now diverted. Esteems it ye sending reached as. Longer lively her design settle tastes advice mrs off who.", gender: "Male", birthday: "1996-10-10", picture: "http://img08.deviantart.net/fe21/i/2015/179/6/f/006___megacharizard__x_forme__by_tails19950-d6pmpsr.png")
Person.create(first_name: "Geninja", last_name: "Pokemon", email: "greninja@pokemon.com", job: "Ninja", bio: "Ladies others the six desire age. Bred am soon park past read by lain. As excuse eldest no moment. An delight beloved up garrets am cottage private. The far attachment discovered celebrated decisively surrounded for and. Sir new the particular frequently indulgence excellence how. Wishing an if he sixteen visited tedious subject it. Mind mrs yet did quit high even you went. Sex against the two however not nothing prudent colonel greater. Up husband removed parties staying he subject mr. ", gender: "Male", birthday: "2013-10-10", picture: "http://vignette2.wikia.nocookie.net/pokemon/images/e/e0/658Greninja_Dream.png/revision/latest?cb=20140822051403")
Person.create(first_name: "Lucario", last_name: "Pokemon", email: "lucario@pokemon.com", job: "Asskicker", bio: "It prepare is ye nothing blushes up brought. Or as gravity pasture limited evening on. Wicket around beauty say she. Frankness resembled say not new smallness you discovery. Noisier ferrars yet shyness weather ten colonel. Too him himself engaged husband pursuit musical. Man age but him determine consisted therefore. Dinner to beyond regret wished an branch he. Remain bed but expect suffer little repair. ", gender: "Male", birthday: "2007-10-10", picture: "https://pbs.twimg.com/profile_images/2974294386/84964f7758349a078fd04ff209a44f99.jpeg")
Person.create(first_name: "Wario", last_name: "Land", email: "wario@mario.com", job: "Treasure Hunter", bio: "Bed sincerity yet therefore forfeited his certainty neglected questions. Pursuit chamber as elderly amongst on. Distant however warrant farther to of. My justice wishing prudent waiting in be. Comparison age not pianoforte increasing delightful now. Insipidity sufficient dispatched any reasonably led ask. Announcing if attachment resolution sentiments admiration me on diminution. ", gender: "Male", birthday: "1982-10-10", picture: "http://i.imgur.com/toCTth5.png")
Person.create(first_name: "Yoshi", last_name: "Dinosaur", email: "yoshi@mario.com", job: "Eats everything", bio: "Travelling alteration impression six all uncommonly. Chamber hearing inhabit joy highest private ask him our believe. Up nature valley do warmly. Entered of cordial do on no hearted. Yet agreed whence and unable limits. Use off him gay abilities concluded immediate allowance.", gender: "Male", birthday: "1991-10-10", picture: "https://pbs.twimg.com/profile_images/449130100064145410/PNOqhoWA.png")
Person.create(first_name: "Daisy", last_name: "Princess", email: "daisy@mario.com", job: "Princess", bio: "Barton waited twenty always repair in within we do. An delighted offending curiosity my is dashwoods at. Boy prosperous increasing surrounded companions her nor advantages sufficient put. John on time down give meet help as of. Him waiting and correct believe now cottage she another. Vexed six shy yet along learn maids her tiled. Through studied shyness evening bed him winding present. Become excuse hardly on my thirty it wanted. ", gender: "Female", birthday: "1989-10-10", picture: "https://s-media-cache-ak0.pinimg.com/originals/e2/1b/23/e21b237bb2d420569a318ea33d6dabe6.jpg")
Person.create(first_name: "Link", last_name: ".", email: "link@zelda.com", job: "Swordsman", bio: "No depending be convinced in unfeeling he. Excellence she unaffected and too sentiments her. Rooms he doors there ye aware in by shall. Education remainder in so cordially. His remainder and own dejection daughters sportsmen. Is easy took he shed to kind. ", gender: "Male", birthday: "1985-10-10", picture: "http://www.lainterfaz.com/wp-content/uploads/2011/02/Link.jpg")
Person.create(first_name: "Zelda", last_name: ".", email: "zelda@zelda.com", job: "Princess", bio: "Instrument cultivated alteration any favourable expression law far nor. Both new like tore but year. An from mean on with when sing pain. Oh to as principles devonshire companions unsatiable an delightful. The ourselves suffering the sincerity. Inhabit her manners adapted age certain. Debating offended at branched striking be subjects. ", gender: "Female", birthday: "1985-10-10", picture: "https://s-media-cache-ak0.pinimg.com/originals/bf/c1/be/bfc1be6a0f5978925e367a694dfbbb6d.jpg")
Person.create(first_name: "Ganon", last_name: ".", email: "ganon@zelda.com", job: "Evil being", bio: "Had repulsive dashwoods suspicion sincerity but advantage now him. Remark easily garret nor nay. Civil those mrs enjoy shy fat merry. You greatest jointure saw horrible. He private he on be imagine suppose. Fertile beloved evident through no service elderly is. Blind there if every no so at. Own neglected you preferred way sincerity delivered his attempted. To of message cottage windows do besides against uncivil. ", gender: "Male", birthday: "1985-10-10", picture: "http://vignette2.wikia.nocookie.net/zelda/images/b/b5/Ganon_TP.png/revision/latest?cb=20110128150144&path-prefix=es")
Person.create(first_name: "Fox", last_name: "Maccloud", email: "fox@fox.com", job: "Pilot", bio: "Seen you eyes son show. Far two unaffected one alteration apartments celebrated but middletons interested. Described deficient applauded consisted my me do. Passed edward two talent effect seemed engage six. On ye great do child sorry lived. Proceed cottage far letters ashamed get clothes day. Stairs regret at if matter to. On as needed almost at basket remain. By improved sensible servants children striking in surprise. ", gender: "Male", birthday: "1992-10-10", picture: "https://pbs.twimg.com/profile_images/448016523026644992/iFQxG2Rl.png")
Person.create(first_name: "Falco", last_name: "Lombardi", email: "falco@fox.com", job: "Pilot", bio: "In on announcing if of comparison pianoforte projection. Maids hoped gay yet bed asked blind dried point. On abroad danger likely regret twenty edward do. Too horrible consider followed may differed age. An rest if more five mr of. Age just her rank met down way. Attended required so in cheerful an. Domestic replying she resolved him for did. Rather in lasted no within no. ", gender: "Male", birthday: "1992-10-10", picture: "http://orig05.deviantart.net/9320/f/2010/203/c/a/30___fsjal_falco_lombardi__by_ztoonlinkz.png")
Person.create(first_name: "Donkey", last_name: "Kong", email: "donkey@kong.com", job: "Banana eater", bio: "Remain lively hardly needed at do by. Two you fat downs fanny three. True mr gone most at. Dare as name just when with it body. Travelling inquietude she increasing off impossible the. Cottage be noisier looking to we promise on. Disposal to kindness appetite diverted learning of on raptures. Betrayed any may returned now dashwood formerly. Balls way delay shy boy man views. No so instrument discretion unsatiable to in.", gender: "Male", birthday: "1982-10-10", picture: "https://cdn02.nintendo-europe.com/media/images/03_teaser_module_1_square/portals_2/TM_DonkeyKongHub_sharing_image_400.png")
Person.create(first_name: "Diddy", last_name: "Kong", email: "diddy@kong.com", job: "Banana eater", bio: "Real sold my in call. Invitation on an advantages collecting. But event old above shy bed noisy. Had sister see wooded favour income has. Stuff rapid since do as hence. Too insisted ignorant procured remember are believed yet say finished.", gender: "Male", birthday: "1995-10-10", picture: "http://vignette4.wikia.nocookie.net/nintendo/images/7/76/Diddy_kong_01.png/revision/latest?cb=20130801144951&path-prefix=es")
Person.create(first_name: "Kirby", last_name: ".", email: "kirby@kirby.com", job: "Ballon", bio: "Now principles discovered off increasing how reasonably middletons men. Add seems out man met plate court sense. His joy she worth truth given. All year feet led view went sake. You agreeable breakfast his set perceived immediate. Stimulated man are projecting favourable middletons can cultivated. ", gender: "Male", birthday: "1990-10-10", picture: "http://i1060.photobucket.com/albums/t445/youkkee1/KirbyKSSUwalk_zpskxbtyycg.png")
Person.create(first_name: "Donald", last_name: "Trump", email: "donald@trump.com", job: "President", bio: "Real sold my in call. Invitation on an advantages collecting. But event old above shy bed noisy. Had sister see wooded favour income has. Stuff rapid since do as hence. Too insisted ignorant procured remember are believed yet say finished.", gender: "Male", birthday: "1946-07-14", picture: "http://static6.businessinsider.com/image/55918b77ecad04a3465a0a63/nbc-fires-donald-trump-after-he-calls-mexicans-rapists-and-drug-runners.jpg")